import Head from 'next/head';
import Category from '../components/category/Category';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Category
          anchor="top"
          categories={() => (
            <>
              <div className="dark:bg-dark-bg-light">1234</div>
            </>
          )}
        />
      </main>
      <footer>{/* footer components */}</footer>
    </div>
  );
}
