import CategoryComponent from '@/components/category/categoryComponent/CategoryComponent';
import { CategoryCollection } from '@/router/category/CategoryResponse';
import axios from '@/router/util/axios';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import React from 'react';

interface HomeProps {
  categoryEntities: CategoryCollection;
}

export default function Home({ categoryEntities }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CategoryComponent categoryEntities={categoryEntities} />
      </main>
      <footer>{/* footer components */}</footer>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (_context) => {
  const result = await axios.get<CategoryCollection>('/api/categories');
  const categoryEntities = result.data;

  return { props: { categoryEntities } };
};
