import Head from 'next/head';
import Category from '../components/categoryWrapper/CategoryWrapper';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Category anchor="top">
          <div className="dark:bg-dark-bg-light">1234</div>
        </Category>
      </main>
      <footer>{/* footer components */}</footer>
    </div>
  );
}
